# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  test_hubbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hub builder step (no push)
        id: hubbuild1  # later we can refer to this step
        uses: ./ # Uses an action in the root directory
        continue-on-error: true
      - name: Get the output
        run: |
          rc=0
          [[ "${{ steps.hubbuild1.outputs.success_targets }}" == ".github/workflows/tests/ImageReader/" ]] || rc=1
          [[ "${{ steps.hubbuild1.outputs.failed_targets }}" == ".github/workflows/tests/EmptyExecutor/" ]] || rc=1
          exit $rc
      - name: Hub builder step (with push)
        id: hubbuild2  # later we can refer to this step
        uses: ./ # Uses an action in the root directory
        continue-on-error: true
        with:
          push: true
          dockerhub_username: ${{secrets.JINAHUB_DOCKER_USER}}
          dockerhub_password: ${{secrets.JINAHUB_DOCKER_PWD}}
      - name: Get the output
        run: |
          rc=0
          [[ "${{ steps.hubbuild2.outputs.success_targets }}" == ".github/workflows/tests/ImageReader/" ]] || rc=1
          [[ "${{ steps.hubbuild2.outputs.failed_targets }}" == ".github/workflows/tests/EmptyExecutor/" ]] || rc=1
          exit $rc